In [1]:
import numpy as np    # it is an unofficial standard to use np for numpy
import time

In [2]:
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64


In [3]:
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64


In [4]:
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.random.random_sample(4): a = [0.81079544 0.9019082  0.75663711 0.59067218], a shape = (4,), a data type = float64


In [7]:
a = np.arange(4);
print(a)

[0 1 2 3]


In [12]:
a = np.random.rand(4);

In [13]:
print(a)

[0.29695667 0.71742993 0.0656303  0.43938697]


In [19]:
ar = np.arange(10)
print(ar)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# Accessing an element
first_element = ar[3]
print(first_element)

3
